// const arr=[1,3,6,4];
// console.log(arr[1]);
// const ar1=new Array(1,3,5,2);
// console.log(ar1[0]);
// ar1.push(12);
// ar1.push(14);
// ar1.pop();
// ar1.unshift(122);
// ar1.shift();
// console.log(ar1);
// console.log(ar1.includes(31));
// console.log(ar1.indexOf(31));
// const arr=[1,2,3,4];
// const newarr=arr.join();
// console.log(arr);
// console.log(newarr);
// console.log(typeof newarr);
// let arr=[1,2,3,4,5,6];
// console.log(arr.slice(0,3));
// console.log(arr);
// console.log(arr.splice(0,3));
// console.log(arr);
// let arr=[1,2,3,4,5,6];
// console.log(arr.slice(1,3));
// console.log(arr);
// console.log(arr.splice(1,3));
// console.log(arr);

// const a=["nitin","prashant"];
// const b=["A","B"];
// a.push(b);
// console.log(a);
// a.concat(b);
// console.log(a);
// const c=a.concat(b);
// console.log(c);
// const e=[...a,...b];
// console.log(e);
// const f=[1,2,3,[4,3,[2,3,4]],[2,3]];
// const g=f.flat(Infinity);
// console.log(g);
// console.log(Array.isArray("Nitin"));
// // console.log(Array.from("Nitin"));
// console.log(Array.from({name:"Nitin"}));
let a=12;
let b=1;
let c=4;


console.log(Array.of(a,b,c));