// const arr=[1,3,6,4];
// console.log(arr[1]);
// const ar1=new Array(1,3,5,2);
// console.log(ar1[0]);
// ar1.push(12);
// ar1.push(14);
// ar1.pop();
// ar1.unshift(122);
// ar1.shift();
// console.log(ar1);
// console.log(ar1.includes(31));
// console.log(ar1.indexOf(31));
// const arr=[1,2,3,4];
// const newarr=arr.join();
// console.log(arr);
// console.log(newarr);
// console.log(typeof newarr);
// let arr=[1,2,3,4,5,6];
// console.log(arr.slice(0,3));
// console.log(arr);
// console.log(arr.splice(0,3));
// console.log(arr);
let arr=[1,2,3,4,5,6];
console.log(arr.slice(1,3));
console.log(arr);
console.log(arr.splice(1,3));
console.log(arr);
